inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - bin/*
    - db/schema.rb
    - node_module/**/*
    - db/migrate/*
    - vendor/**/*
  Rails:
    enabled: true

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/FrozenStringLiteralCommnet:
  Enabled: false