version: '3'
services:
  web:
    build: .
    env_file: .docker-env
    # command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app:cached
    ports:
      - 3000:3000
    depends_on:
      - db
    tty: true
    stdin_open: true
    entrypoint: bash -c
    command: |
      "bundle install && \
      bundle exec rails s -b 0.0.0.0 -p 3000"
  db:
    image: mysql:5.7
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3306:3306
volumes:
  db-volume:

